{ config, lib, pkgs, modulesPath, ... }:

{
  # This will be generated by nixos-anywhere during installation
  # Placeholder for now
  imports = [ ];
  
  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
